#!/bin/bash

sudo apt-get update
sudo apt-get install libsdl-ttf2.0-dev
sudo apt-get install libgtk-3-dev
sudo apt-get install libsdl1.2-dev
sudo apt-get install libghc-sdl-gfx-dev 
sudo apt-get install libsdl-image1.2-dev 