#!/bin/bash

sudo apt-get update

sudo apt install build-essential -y
sudo apt install make  -y

sudo apt-get install libsdl-ttf2.0-dev -y
sudo apt-get install libgtk-3-dev -y 
sudo apt-get install libsdl1.2-dev -y
sudo apt-get install libsdl-gfx1.2-dev -y
sudo apt-get install libsdl-image1.2-dev -y